# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_about__Form(object):
    def setupUi(self, about__Form):
        about__Form.setObjectName("about__Form")
        about__Form.resize(460, 180)
        self.centralwidget = QtWidgets.QWidget(about__Form)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 10, 150, 58))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("46023.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 96, 371, 71))
        self.label_2.setAutoFillBackground(False)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(120, 65, 54, 23))
        self.label_3.setObjectName("label_3")
        self.ver_label = QtWidgets.QLabel(self.centralwidget)
        self.ver_label.setGeometry(QtCore.QRect(174, 65, 161, 23))
        self.ver_label.setText("")
        self.ver_label.setObjectName("ver_label")
        about__Form.setCentralWidget(self.centralwidget)

        self.retranslateUi(about__Form)
        QtCore.QMetaObject.connectSlotsByName(about__Form)

    def retranslateUi(self, about__Form):
        _translate = QtCore.QCoreApplication.translate
        about__Form.setWindowTitle(_translate("about__Form", "关于工具"))
        self.label_2.setText(_translate("about__Form", "<html><head/><body><p>    通联日志记录工具是用于记录中继台网点名、个人通联记录存档，由于本人非专业开发人员，仅为个人爱好且不专业，故而工具可能出现各种奇奇怪怪的Bug，敬请谅解！</p><p align=\"center\">Copyright(c)2024 The MMDVM-TG46023.</p></body></html>"))
        self.label_3.setText(_translate("about__Form", "Version:"))
