# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'changeop.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QDialog, QLineEdit, QPushButton
from PyQt5.uic import loadUi
from PyQt5.QtCore import pyqtSignal



class Ui_opchange__Form(object):
    def setupUi(self, opchange__Form):
        opchange__Form.setObjectName("opchange__Form")
        opchange__Form.resize(318, 102)
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体 2.0 55 Regular")
        font.setPointSize(13)
        opchange__Form.setFont(font)
        self.changeop_callsign = QtWidgets.QLineEdit(opchange__Form)
        self.changeop_callsign.setGeometry(QtCore.QRect(146, 17, 160, 30))
        self.changeop_callsign.setObjectName("changeop_callsign")
        self.label = QtWidgets.QLabel(opchange__Form)
        self.label.setGeometry(QtCore.QRect(10, 20, 140, 31))
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体 2.0 55 Regular")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.changeop_ok_Button = QtWidgets.QPushButton(opchange__Form)
        self.changeop_ok_Button.setGeometry(QtCore.QRect(110, 60, 90, 30))
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体 2.0 55 Regular")
        font.setPointSize(13)
        self.changeop_ok_Button.setFont(font)
        self.changeop_ok_Button.setObjectName("changeop_ok_Button")

        self.retranslateUi(opchange__Form)
        QtCore.QMetaObject.connectSlotsByName(opchange__Form)

    def retranslateUi(self, opchange__Form):
        _translate = QtCore.QCoreApplication.translate
        opchange__Form.setWindowTitle(_translate("opchange__Form", "变更操作员"))
        self.changeop_callsign.setPlaceholderText(_translate("opchange__Form", "请输入操作员呼号"))
        self.label.setText(_translate("opchange__Form", "操作员（OP）："))
        self.changeop_ok_Button.setText(_translate("opchange__Form", "确认变更"))

class ChangeOpWindow(QDialog):
    content_changed_signal = pyqtSignal(str)

    def __init__(self, initial_content, parent=None):
        super().__init__(parent)
        self.ui = loadUi('changeop.ui', self)  # 假设opchange.ui是你的界面文件
        self.ui.changeop_callsign.setText(initial_content)  # 设置输入框默认值
        self.ui.changeop_ok_Button.clicked.connect(self.on_ok_clicked)  # 直接连接确认按钮的点击事件

    def on_ok_clicked(self):
        new_content = self.ui.changeop_callsign.text()
        self.content_changed_signal.emit(new_content)
        self.close()  # 点击确认按钮后关闭窗口

# 若要在其他地方使用这个窗口，确保导入这个类并实例化
