# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'del_log_pwd.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QDialog, QLineEdit, QPushButton, QMainWindow
from PyQt5.uic import loadUi
from PyQt5.QtCore import pyqtSignal, QRegularExpression
from PyQt5.QtGui import QRegularExpressionValidator

class Ui_del_pwd_set_Form(object):
    def setupUi(self, del_pwd_set_Form):
        del_pwd_set_Form.setObjectName("del_pwd_set_Form")
        del_pwd_set_Form.resize(318, 118)
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体 2.0 55 Regular")
        font.setPointSize(13)
        del_pwd_set_Form.setFont(font)
        self.label = QtWidgets.QLabel(del_pwd_set_Form)
        self.label.setGeometry(QtCore.QRect(10, 20, 121, 30))
        self.label.setObjectName("label")
        self.changeop_redme_label = QtWidgets.QLabel(del_pwd_set_Form)
        self.changeop_redme_label.setGeometry(QtCore.QRect(10, 50, 301, 30))
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体 2.0 45 Light")
        font.setPointSize(9)
        self.changeop_redme_label.setFont(font)
        self.changeop_redme_label.setAlignment(QtCore.Qt.AlignCenter)
        self.changeop_redme_label.setWordWrap(False)
        self.changeop_redme_label.setObjectName("changeop_redme_label")
        self.dellog_pwd_lineEdit = QtWidgets.QLineEdit(del_pwd_set_Form)
        self.dellog_pwd_lineEdit.setGeometry(QtCore.QRect(129, 17, 170, 30))
        self.dellog_pwd_lineEdit.setObjectName("dellog_pwd_lineEdit")
        self.change_delpwd_Button = QtWidgets.QPushButton(del_pwd_set_Form)
        self.change_delpwd_Button.setGeometry(QtCore.QRect(110, 80, 90, 30))
        self.change_delpwd_Button.setObjectName("change_delpwd_Button")

        self.retranslateUi(del_pwd_set_Form)
        QtCore.QMetaObject.connectSlotsByName(del_pwd_set_Form)

    def retranslateUi(self, del_pwd_set_Form):
        _translate = QtCore.QCoreApplication.translate
        del_pwd_set_Form.setWindowTitle(_translate("del_pwd_set_Form", "修改日志删除密码"))
        self.label.setText(_translate("del_pwd_set_Form", "日志删除密码："))
        self.changeop_redme_label.setText(_translate("del_pwd_set_Form", "默认密码：123456，仅为防误删，建议可以不修改！"))
        self.change_delpwd_Button.setText(_translate("del_pwd_set_Form", "更改密码"))


class DelPwdSetWindow(QMainWindow, Ui_del_pwd_set_Form):
    password_changed_signal = pyqtSignal(str)  # 定义一个信号，用于通知密码变更

    def __init__(self, parent=None):
        super().__init__(parent)
        self.setupUi(self)

        # 为dellog_pwd_lineEdit设置验证器，只允许输入大小写字母和数字，且最多32位
        regex = QRegularExpression(r'^[A-Za-z0-9]{1,32}$')  # 匹配1到32个连续的字母或数字
        validator = QRegularExpressionValidator(regex, self.dellog_pwd_lineEdit)
        self.dellog_pwd_lineEdit.setValidator(validator)

        # 当点击change_delpwd_Button按钮时，执行密码更改相关的操作
        self.change_delpwd_Button.clicked.connect(self.handle_password_change)

    def handle_password_change(self):
        # 获取密码输入并做进一步的处理
        new_password = self.dellog_pwd_lineEdit.text().strip()  #无法执行
        # 在处理完密码更改逻辑后，发射信号
        # new_password = self.dellog_pwd_lineEdit.text().trimmed()
        self.password_changed_signal.emit(new_password)
        # 这里可以根据需要进行其他密码验证逻辑，如存储、验证强度等
        self.close()