# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'changeop.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_opchange__Form(object):
    def setupUi(self, opchange__Form):
        opchange__Form.setObjectName("opchange__Form")
        opchange__Form.resize(318, 118)
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体 2.0 55 Regular")
        font.setPointSize(13)
        opchange__Form.setFont(font)
        self.changeop_callsign = QtWidgets.QLineEdit(opchange__Form)
        self.changeop_callsign.setGeometry(QtCore.QRect(146, 17, 160, 30))
        self.changeop_callsign.setObjectName("changeop_callsign")
        self.label = QtWidgets.QLabel(opchange__Form)
        self.label.setGeometry(QtCore.QRect(10, 20, 140, 31))
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体 2.0 55 Regular")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.changeop_ok_Button = QtWidgets.QPushButton(opchange__Form)
        self.changeop_ok_Button.setGeometry(QtCore.QRect(110, 80, 90, 30))
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体 2.0 55 Regular")
        font.setPointSize(13)
        self.changeop_ok_Button.setFont(font)
        self.changeop_ok_Button.setObjectName("changeop_ok_Button")
        self.changeop_redme_label = QtWidgets.QLabel(opchange__Form)
        self.changeop_redme_label.setGeometry(QtCore.QRect(10, 50, 301, 30))
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体 2.0 45 Light")
        font.setPointSize(9)
        self.changeop_redme_label.setFont(font)
        self.changeop_redme_label.setAlignment(QtCore.Qt.AlignCenter)
        self.changeop_redme_label.setWordWrap(False)
        self.changeop_redme_label.setObjectName("changeop_redme_label")

        self.retranslateUi(opchange__Form)
        QtCore.QMetaObject.connectSlotsByName(opchange__Form)

    def retranslateUi(self, opchange__Form):
        _translate = QtCore.QCoreApplication.translate
        opchange__Form.setWindowTitle(_translate("opchange__Form", "变更操作员"))
        self.changeop_callsign.setPlaceholderText(_translate("opchange__Form", "请输入操作员呼号"))
        self.label.setText(_translate("opchange__Form", "操作员（OP）："))
        self.changeop_ok_Button.setText(_translate("opchange__Form", "确认变更"))
        self.changeop_redme_label.setText(_translate("opchange__Form", "呼号不分大小写，可以输入BG8LAK或B7/BG8LAK）"))
